# Checking the Data Type of an Array

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 5, 4])

print(arr.dtype)

int32


In [2]:
import numpy as np

arr1 = np.array(['hello', 'world!'])

print(arr1.dtype)

<U6


# Creating Arrays With a Defined Data Type

In [4]:
#Create an array with data type string:
import numpy as np

arr2 = np.array([1, 2, 3], dtype='S')

print(arr2)
print(arr2.dtype)

[b'1' b'2' b'3']
|S1


In [5]:
import numpy as np

arr3 = np.array([1, 2, 3], dtype='i4')    #Create an array with data type 3 bytes integer:

print(arr3)
print(arr3.dtype)

[1 2 3]
int32


# Converting Data Type on Existing Arrays

In [7]:
import numpy as np

arr4 = np.array([1.1, 2.1, 3.1])

newarr = arr4.astype('i')    #change data type from float to integer by using 'i' as parameter value

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [12]:
import numpy as np

arr5 = np.array([1, 0, 1, 0])

newarr = arr5.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True False]
bool


In [13]:
import numpy as np

arr6 = np.array([1.1, 2.1, 3.1])

newarr = arr6.astype(int)    #Change data type from float to integer by using int as parameter value

print(newarr)
print(newarr.dtype)

[1 2 3]
int32
