In [9]:
import numpy as np
a = np.matrix([[5, 6, 7], [4, 6]])
b = np.matrix([[1, 2, 3],[4, 5]])

print("Matrix A is : \n\n")
print(a)

print("Matrix B is : \n\n")
print(b)

Matrix A is : 


[[list([5, 6, 7]) list([4, 6])]]
Matrix B is : 


[[list([1, 2, 3]) list([4, 5])]]


In [11]:
import numpy as np
a = np.array([[5, 7], [4, 6]])
b = np.array([[1, 3], [4, 5]]) 
c = np.asmatrix(a)         #converting numpy array to a matrix
d = np.asmatrix(b)

print("Matrix c is : \n\n")
print(c)

print("Matrix d is : \n\n")
print(d)

Matrix c is : 


[[5 7]
 [4 6]]
Matrix d is : 


[[1 3]
 [4 5]]


In [13]:
import numpy as np
a = np.array([[5, 7], [4, 6]])
b = np.array([[1, 3], [4, 5]]) 

print('Multiplication of a and  b is:')
print(a*b)    # element by element multiplication 

c = np.matrix([[5, 7],[4, 6]])
d = np.matrix([[2, 3],[4, 5]])

print('Dot product of c and  d is:')

print(np.multiply(c,d))       #dot product

Multiplication of a and  b is:
[[ 5 21]
 [16 30]]
Dot product of a and  b is:
[[10 21]
 [16 30]]


In [17]:
import numpy as np
  
a = np.array([[2, 4, 6],[1, 3, 5]])
   
print ("array a :\n ",a) 
    
b = np.cumsum(a) 
print("cumulative sum of array elements: ",b) 

array a :
  [[2 4 6]
 [1 3 5]]
cumulative sum of array elements:  [ 2  6 12 13 16 21]


In [18]:
import numpy as np
  
a = np.array([[2, 4, 6], [1, 3, 5]])
   
print ("Input array : ",a) 
    
b = np.cumsum(a, axis = 1)     #cumulative sum by taking axis =1

print("cumulative sum of array elements taking axis 1: ",b) 

Input array :  [[2 4 6]
 [1 3 5]]
cumulative sum of array elements taking axis 1:  [[ 2  6 12]
 [ 1  4  9]]
