In [33]:
# Python program to demonstrate 
# the use of index arrays.
import numpy as np
 
# Create a sequence of integers from
# 10 to 1 with a step of -2
a = np.arange(10, 2, -2) 
print("\n A sequential array with a negative step: \n",a)
 
# Indexes are specified inside the np.array method.
newarr = a[np.array([3, 1, 2 ])]
print("\n Elements at these indices are:\n",newarr)


 A sequential array with a negative step: 
 [10  8  6  4]

 Elements at these indices are:
 [4 8 6]


In [34]:
import numpy as np
arr=np.array([1,6,7,8,3,5])
print(arr[2] + arr[4])         #addition by indexing

10


# accessing 2-D array elements 

In [35]:
a = [ [72, 85, 87, 90, 69], [80, 87, 65, 89, 85], [96, 91, 70, 78, 97], [90, 93, 91, 90, 94], [57, 89, 82, 69, 60] ]  
#print(a)  
print(a[1]) # print all elements of index 1  
print(a[0]) # print all elements of index 0  
print(a[2]) # print all elements of index 2

[80, 87, 65, 89, 85]
[72, 85, 87, 90, 69]
[96, 91, 70, 78, 97]


# accessing 3-D array elements

In [36]:
import numpy as np

arr1 = np.array([[[2,17], [45, 78]], [[88, 92], [60, 76]],[[76,33],[20,18]]])
print("Create 3-d array:",arr1)
print(arr1.ndim)
print(arr1.shape)

Create 3-d array: [[[ 2 17]
  [45 78]]

 [[88 92]
  [60 76]]

 [[76 33]
  [20 18]]]
3
(3, 2, 2)


In [37]:
import numpy as np
list=[1,2,3,4,4]
arr=np.array(list)
print(arr[[2,3]])  #print elements present atindex 2 and 3

[3 4]


In [38]:
import numpy as np
b=np.array([[[2,17],[20,18]]])  #3-d array
print(b)
print(b[0,1,0])


[[[ 2 17]
  [20 18]]]
20


In [39]:
import numpy as np
c = np.array([ [72, 85, 87], [80, 87, 85], [96, 91, 70], [57, 69, 60] ])
print(c)
print(c[1,1])

[[72 85 87]
 [80 87 85]
 [96 91 70]
 [57 69 60]]
87


In [40]:
import numpy as np
arr3=np.array([1,6,7,8,3,5])
print(arr3[-4])

7


In [41]:
import numpy as np
arr4=np.array([[1,6,7,8,3,5]])
print(arr4[0,-4])

7


In [42]:
import numpy as np
list1=[1,2,3,4,4]
arr5=np.array(list1)
print(arr5)            
print(arr5>3)             #boolean indexing

[1 2 3 4 4]
[False False False  True  True]


In [43]:
import numpy as np
list1=[1,2,3,4,4]
arr5=np.array(list1)
print(arr5)            
print(arr5[arr5>3])

[1 2 3 4 4]
[4 4]


In [44]:
import numpy as np
num=np.arange(10)
print(num)
odd_num= num[num % 2 == 1]    #odd numbers from given range
print(odd_num)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
