In [9]:
import numpy as np
list1=[1,4,5,6,7]
arr=np.array(list1)
print(arr)
print(type(arr))

[1 4 5 6 7]
<class 'numpy.ndarray'>


In [10]:
import numpy as np
set={1,4,5,6,7}
arr=np.array(set)
print(arr)
print(type(arr))

{1, 4, 5, 6, 7}
<class 'numpy.ndarray'>


In [11]:
import numpy as np
tuple=[1,4,5,6,7]
arr=np.array(tuple)
print(arr)
print(type(arr))

[1 4 5 6 7]
<class 'numpy.ndarray'>


In [12]:
arr=np.array(15)
print(arr)   #printing 0-dimensional array

15


In [13]:
list=(15,30,90,66,84)
arr=np.array(list)
print(arr)   #printing 1-dimensional array

[15 30 90 66 84]


In [14]:
import numpy as np 
arr=np.array([[1,2,3] , [5,6,7]])
print(arr)     #printing 2-dimensional array


[[1 2 3]
 [5 6 7]]


In [15]:
import numpy as np

a=np.array(13)
b=np.array([1,2,4,5])
c=np.array([[1,2,3] , [5,6,7]])
print("Dimension of a is:",a.ndim)
print("Dimension of b is:",b.ndim)
print("Dimension of c is:",c.ndim)

Dimension of a is: 0
Dimension of b is: 1
Dimension of c is: 2
