In [2]:
# list of integers
my_list = [1, 2, 3]
print(my_list)


[1, 2, 3]


In [3]:
# list with mixed data types
my_list = [1, "Hello", 3.4]
print(my_list)

[1, 'Hello', 3.4]


# Creating NumPy arrays

In [5]:
import numpy as np  #importing numpy library

In [8]:
x= np.arange(5) #create a range from 0-4
print(x)
print(x.shape)

[0 1 2 3 4]
(5,)


In [10]:
x1 = np.arange(1,500,10) #initializing numpy array within a range with a gap of 10 numbers
print(x1)

[  1  11  21  31  41  51  61  71  81  91 101 111 121 131 141 151 161 171
 181 191 201 211 221 231 241 251 261 271 281 291 301 311 321 331 341 351
 361 371 381 391 401 411 421 431 441 451 461 471 481 491]


In [12]:
import numpy as np    
x2 =np.zeros((1,9))    #initializing numpy array with zeros
print(x2)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [16]:
import numpy as np
x3=np.zeros((5,5))  #initializing numpy array with zeros 
print(x3)
print(x3.shape)     #checking the shape of the array

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(5, 5)


In [17]:
import numpy as np
x4=np.full((2,5),10)
x4

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [18]:
import numpy as np
x5=np.random.randint(1,100,5)   # printing 5 random numbers from 1-100
x5

array([28, 26, 51, 72, 55])

In [19]:
list1=[1,8,9,5,6,]   
x6=np.array(list1)    #
print(list1)     #printing given list 

[1, 8, 9, 5, 6]
