In [16]:
import numpy as np

arr = np.array([3, 2, 0, 6, 8, 9, 1])
print('Original array is:',arr)
print('Sorted array is:',np.sort(arr))   #print sorted array

Original array is: [3 2 0 6 8 9 1]
Sorted array is: [0 1 2 3 6 8 9]


In [17]:
import numpy as np

arr1 = np.array(['Apple', 'Tiger', 'Zebra', 'Mango'])
print('Original array is:',arr1)
print('Sorted array is')
print(np.sort(arr1))   #sort arrays of strings

Original array is: ['Apple' 'Tiger' 'Zebra' 'Mango']
Sorted array is
['Apple' 'Mango' 'Tiger' 'Zebra']


In [18]:
import numpy as np
  
# input array
arr = np.array([ 2, 0,  1, 5, 4, 1, 9])
print ("Input unsorted array : ", arr) 

print ("Output sorted array indices : ", np.argsort(arr))


Input unsorted array :  [2 0 1 5 4 1 9]
Output sorted array indices :  [1 2 5 0 4 3 6]


In [19]:

import numpy as np
 
arr = np.array([49, 7, 44, 27, 13, 35, 71])
 
sorted_array = np.sort(arr)[::-1]    #printing array in descending order
print(sorted_array)

[71 49 44 35 27 13  7]


In [20]:
arr = np.array([7, 5, 3, 2, 6, 1, 4])

sorted_array = np.sort(arr)       # Sort in ascending order

reverse_array = sorted_array[::-1]     # Reverse the sorted array
print(sorted_array)
print(reverse_array)

[1 2 3 4 5 6 7]
[7 6 5 4 3 2 1]
