# NumPy array slicing 

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])   # NumPy array with elements from 1 to 7

print(arr[1:5])

[2 3 4 5]


In [2]:
#Negative slicing
#Slice from the index 3 from the end to index 1 from the end:

import numpy as np

arr1 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr1[-3:-1])

[5 6]


In [4]:
import numpy as np

arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr2)

print(arr2[1, 1:4])     #Slicing 2-D Arrays   #From the second element, slice elements from index 1 to index 4 (not included)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]


In [5]:
import numpy as np

arr3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])    # NumPy array with elements from 1 to 9

print(arr3[4:])

[5 6 7 8 9]


In [6]:
import numpy as np

arr4 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])    # NumPy array with elements from 1 to 9
print(arr4[:4])

[1 2 3 4]


In [7]:
import numpy as np

arr5 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr5[1:4:3])

[2]


In [8]:
import numpy as np

arr6 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])   #2D array
print(arr6[0:1, 3])

[4]


In [9]:
import numpy as np

arr7 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])   #2D array

print(arr7[0:1, 3])
print(arr7.shape)   #finding the shape of sliced array

[4]
(2, 5)


In [11]:
import numpy as np

arr8 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr8[1:4:3])
print(arr8.shape)

[2]
(9,)
