In [3]:
import numpy as np
arr1 = np.array([[2, 5], [-6, 0]])
arr2 = np.array([[5, 5], [3, 9]])
print("Addition is:")
print(arr1+arr2)    #Addition of two arrays

Addition is:
[[ 7 10]
 [-3  9]]


In [4]:
import numpy as np
arr3 = np.array([[2,4, 5], [-6,3,0]])
arr4 = np.array([[5,10, 5], [3,9, 9]])
print("Addition is:")
print(arr3+arr4) 

Addition is:
[[ 7 14 10]
 [-3 12  9]]


In [5]:
import numpy as np
arr1 = np.array([[2, 5], [-6, 0]])
arr2 = np.array([[5, 5], [3, 9]])
print("Addition is:")
print(np.add(arr1,arr2))    #addition using np.add method.

Addition is:
[[ 7 10]
 [-3  9]]


In [6]:
#similarly we can subtract , multiply and divide numpy arrays
import numpy as np
arr1 = np.array([[2, 5], [-6, 0]])
arr2 = np.array([[5, 5], [3, 9]])
print("Subtraction  is:")
print(np.subtract(arr1,arr2))

Subtraction  is:
[[-3  0]
 [-9 -9]]


In [7]:
import numpy as np
arr1 = np.array([[2, 5], [-6, 0]])
arr2 = np.array([[5, 5], [3, 9]])
print("Multiplication  is:")
print(np.multiply(arr1,arr2))

Multiplication  is:
[[ 10  25]
 [-18   0]]


In [8]:
import numpy as np
arr1 = np.array([[2, 5], [-6, 0]])
arr2 = np.array([[5, 5], [3, 9]])
print("Division is:")
print(np.divide(arr1,arr2))

Division is:
[[ 0.4  1. ]
 [-2.   0. ]]


In [12]:
import numpy as np
names = np.array(['A','B','C'])
height = np.array([1.5, 1.7, 1.4])
weight = np.array([88, 49, 30])

BMI= weight/height  **2    #finding bmi
print('The bmi of A , B, and C is:',BMI)
print('Overweight:',names[BMI>25])
print('Underweigth:',names[BMI<18.5])
print('Healthy',names[(BMI>=18.5) & (BMI<=25)])

The bmi of A , B, and C is: [39.11111111 16.9550173  15.30612245]
Overweight: ['A']
Underweigth: ['B' 'C']
Healthy []


In [13]:
import numpy as np
arr1 = np.array([[2, 5], [-6, 0]])
arr2 = np.array([[5, 5], [3, 9]])
print("Dot product is:")
print(np.divide(arr1,arr2)) 

Dot product is:
[[ 0.4  1. ]
 [-2.   0. ]]
